"""
Streamlit UI for Broadway Show Research System
"""

import streamlit as st
import time
from main import run_pipeline

# Page configuration
st.set_page_config(
    page_title="Broadway Researcher",
    page_icon="🎭",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# Custom CSS
st.markdown("""
<style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    .stDeployButton {display:none;}
    
    .header-title {
        font-size: 2.5rem;
        font-weight: 700;
        color: rgb(59, 130, 246);
        text-align: center;
        margin-bottom: 0.5rem;
    }
    
    .header-subtitle {
        color: #666;
        font-size: 1rem;
        font-weight: 400;
        text-align: center;
        margin-bottom: 2rem;
    }
    
    .stButton>button {
        background: linear-gradient(to right, rgb(59, 130, 246), rgb(99, 179, 237));
        color: white !important;
        font-size: 1.125rem !important;
        font-weight: 600 !important;
        border: none !important;
        border-radius: 6px !important;
        transition: all 0.2s !important;
        width: 100%;
    }
    
    .stButton>button:hover {
        background: linear-gradient(to right, rgba(59, 130, 246, 0.9), rgba(99, 179, 237, 0.9)) !important;
        transform: translateY(-1px);
    }

    .stTextInput>div>div>input {
        border-radius: 6px;
        padding: 1rem;
        font-size: 1.1rem;
        border: 2px solid #e0e0e0;
    }
    
    .stTextInput>div>div>input:focus {
        border-color: rgb(59, 130, 246);
    }
    
    h3 {
        color: black !important;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown("""
<div class="header-title">Broadway Researcher</div>
<div class="header-subtitle">Your AI-powered theater guide to Broadway shows</div>
""", unsafe_allow_html=True)

st.markdown("### Enter a Broadway Show Name")

show_name = st.text_input(
    "Search",
    placeholder="e.g., Hamilton, Wicked, The Lion King...",
    label_visibility="collapsed",
    key="search_input"
)

# Big button at the bottom
st.markdown("<br>", unsafe_allow_html=True)
search_button = st.button("Search", use_container_width=True)

# Results section
if search_button and show_name:
    with st.spinner('Researching with AI agents...'):
        start_time = time.time()
        
        try:          
            result = run_pipeline(show_name)
            
            # Display result
            st.markdown(result["report"])
            
            # Download button with extended report
            extended_report = result.get("extended_report", result["report"])
            report_text = f"""Broadway Show Research Report - Extended
Generated for: {show_name}

{extended_report}

---
Report generated by Broadway Researcher
Powered by Tavily Search & OpenAI
"""
            
            st.download_button(
                label="📥 Download Report",
                data=report_text,
                file_name=f"{show_name.replace(' ', '_')}_research.txt",
                mime="text/plain",
                use_container_width=True
            )
            
        except Exception as e:
            error_msg = str(e)
            
            # Determine more specific error message
            if "API" in error_msg or "key" in error_msg.lower():
                st.error("❌ API Authentication Error")
                st.warning("Unable to connect to OpenAI or Tavily API. Please check your API keys.")
            elif "connection" in error_msg.lower() or "timeout" in error_msg.lower():
                st.error("❌ Connection Error")
                st.warning("Unable to connect to the services. Please check your internet connection.")
            else:
                st.error(f"❌ Error: {error_msg}")
            
            # Show setup help
            with st.expander("🔧 Setup Needed", expanded=True):
                st.markdown("""
                To fix this issue - restart the application
                """)

elif search_button and not show_name:
    st.warning("Please enter a Broadway show name")



# Footer
st.markdown("---")
st.markdown(
    """
    <div style="text-align: center; color: #666; padding: 2rem 0;">
        <p style="font-size: 0.9rem;">Built with Tavily Search & OpenAI</p>
    </div>
    """,
    unsafe_allow_html=True
)